export default {
    GET_BASIC_INFO: 'GET_BASIC_INFO',
    GET_MENUITEM_LIST: 'GET_MENUITEM_LIST',
    GET_BANLANCELIST: 'GET_BANLANCELIST',
    GET_USER_SCORE: 'GET_USER_SCORE',
    GET_SCHEDULAR_LIST: 'GET_SCHEDULAR_LIST'
}