export default {
    GET_BASIC_INFO: 'GET_BASIC_INFO',
    GET_MENUITEM_LIST: 'GET_MENUITEM_LIST',
    GET_BANLANCE_LIST: 'GET_BANLANCE_LIST',
    GET_USER_SCORE: 'GET_USER_SCORE',
    GET_SCHEDULAR_LIST: 'GET_SCHEDULAR_LIST',
    GET_COUPON_LIST: 'GET_COUPON_LIST',
    GET_PLUS_INFO: 'GET_PLUS_INFO',
    GET_EQUITY_LIST: 'GET_EQUITY_LIST'

}