export default {
  GET_CLASSIFY_HOME: "GET_CLASSIFY_HOME", //类型列表
  GET_TOUR_LIST: "GET_TOUR_LIST", //会员折扣轮播图
  GET_HOTS_RECOMMENDLIST: "GET_HOTS_RECOMMENDLIST", //热门演出
  GET_TOUR_SHOWLIST: "GET_TOUR_SHOWLIST", //巡回演出
  GET_SHOW_LIST: "GET_SHOW_LIST", //瀑布流所需要的的数据
  GET_FLOOR_SHOW: "GET_FLOOR_SHOW", //舞台剧 选项列表
};
